import styles from './TermsPage.module.css';

type TermSection = {
  title: string;
  body: string[];
};

const TERMS_SECTIONS: TermSection[] = [
  {
    title: 'Best Price Offer',
    body: [
      "AT ASII MEDICAL, WE OFFER THE BEST PRICE AND WILL TRY TO MATCH ANY AUTHORIZED MANUFACTURER'S PRICING FOR MOST ITEMS. (NOTE: SOME MANUFACTURERS MAY BE EXCLUDED.) IF YOU FIND A LOWER PRICE, PLEASE CALL US AT 919-444-2339.",
    ],
  },
  {
    title: 'Minimum Order Requirements',
    body: [],
  },
  {
    title: 'Domestic Shipping',
    body: [
      'FOR SHIPMENTS WITHIN THE USA AND ITS TERRITORIES, THERE IS A MINIMUM ORDER REQUIREMENT OF $300.00. ORDERS PLACED UNDER THIS MINIMUM MAY BE SUBJECT TO A $25.00 MINIMUM ORDER FEE, IN ADDITION TO FREIGHT CHARGES, OR MAY RESULT IN THE CANCELLATION OF THE ORDER.',
    ],
  },
  {
    title: 'International Shipping',
    body: [
      'FOR INTERNATIONAL SHIPMENTS, A MINIMUM ORDER REQUIREMENT OF $2,500.00 APPLIES. A $100.00 PROCESSING FEE WILL BE ADDED, ALONG WITH FREIGHT CHARGES. PLEASE NOTE THAT PAYMENT MUST BE MADE VIA WIRE TRANSFER TO PROCESS THE ORDER.',
    ],
  },
  {
    title: 'Shipping Charges',
    body: [
      'SHIPPING CHARGES VARY BASED ON FACTORS SUCH AS PACKAGE WEIGHT, DIMENSIONS, NUMBER OF PACKAGES, PERISHABILITY, URGENCY, AND DELIVERY LOCATION. SHIPPING FEES START AT $9.50 FOR MOST ORDERS. YOU MAY SPECIFY A PREFERRED CARRIER BY INFORMING OUR CUSTOMER SERVICE TEAM DURING YOUR ORDER PLACEMENT, OR BY ADDING A NOTE IN THE COMMENT SECTION IF ORDERING ONLINE. YOU CAN ALSO REQUEST TO BILL SHIPPING TO YOUR ACCOUNT NUMBER.',
    ],
  },
  {
    title: 'Delivery Terms',
    body: [
      'OUR SHIPPING TERMS ARE FOB: ORIGIN. ASII MEDICAL IS NOT RESPONSIBLE FOR SHIPMENTS ONCE THEY LEAVE OUR DOCK. FOR AN ADDITIONAL FEE, YOUR SHIPMENT MAY BE INSURED; PLEASE CONTACT OUR CUSTOMER SERVICE FOR DETAILS.',
    ],
  },
  {
    title: 'Expedited Shipping',
    body: [
      'EXPEDITED SHIPPING TRANSIT TIMES BEGIN FROM THE MOMENT THE PRODUCT IS SHIPPED FROM OUR FACILITY. PLEASE BE AWARE THAT NOT ALL ITEMS LISTED ON OUR WEBSITE ARE STOCKED ON-SITE AND MAY TAKE 1 TO 3 WEEKS TO ARRIVE FOR SHIPPING. IF YOUR ORDER IS TIME-SENSITIVE, PLEASE CONTACT US FOR SPECIFIC AVAILABILITY.',
    ],
  },
  {
    title: 'Drop Shipped Items',
    body: [
      'ITEMS THAT ARE DROP SHIPPED DIRECTLY FROM THE MANUFACTURER MAY HAVE VARYING SHIPPING TIMES AND MAY BE SUBJECT TO QUALIFICATION PERIODS. SOME MANUFACTURERS MAY RESTRICT EXPEDITED SHIPPING REQUESTS. ALL ORDERS MAY INCUR ADDITIONAL FEES AND TAXES AS PER STATE LAWS AND MANUFACTURER REQUIREMENTS.',
    ],
  },
  {
    title: 'Sales Tax',
    body: [
      'SALES TAX MAY BE APPLICABLE FOR CUSTOMERS IN NORTH CAROLINA AND FOR CERTAIN DROP-SHIPPED ITEMS FROM OTHER STATES. THIS DOES NOT EXEMPT CUSTOMERS FROM OTHER STATES FROM THEIR TAX OBLIGATIONS. TAX RATES ON ORDERS ARE SUBJECT TO CHANGE BASED ON FEDERAL AND STATE REGULATIONS.',
    ],
  },
  {
    title: 'Returns & Cancellations',
    body: [
      'IMPORTANT: DUE TO FDA GUIDELINES AND SUPPLY CHAIN DEMANDS, ALL ORDERS AND PRODUCTS RELATED TO COVID-19 ARE NON-CANCELLABLE AND NON-RETURNABLE.',
      'ELIGIBLE ITEMS FOR RETURN ARE SUBJECT TO A 25% RESTOCKING FEE AND MUST INCLUDE A RETURN AUTHORIZATION, WHICH CAN BE OBTAINED BY CONTACTING ASII MEDICAL AT 919-444-2339. CUSTOMERS ARE RESPONSIBLE FOR RETURN FREIGHT. RETURNED ITEMS MUST BE SHIPPED BACK WITHIN 30 DAYS OF SHIPMENT AND WITHIN 14 DAYS OF RECEIVING THE RETURN AUTHORIZATION. PRODUCTS AND PACKAGING MUST BE IN RESALEABLE CONDITION. NOTE THAT LABELS ON EXTERIOR PACKAGING WILL RENDER THE ITEM NON-RESALEABLE.',
      'NON-RETURNABLE ITEMS: REFRIGERATED ITEMS, PHARMACEUTICALS, INJECTABLES, REAGENT TEST CASSETTES, AND MOST NON-STOCK ITEMS ARE NOT ELIGIBLE FOR RETURN.',
      'FOR DEFECTIVE ITEMS OR SHIPPING ERRORS, ASII MEDICAL OR THE ORIGINAL MANUFACTURER WILL COVER THE RESPONSIBILITY. ANY SHIPPING DISCREPANCIES MUST BE REPORTED WITHIN 7 DAYS OF RECEIPT.',
    ],
  },
  {
    title: 'Product Disclaimer',
    body: [
      "PLEASE NOTE: IMAGES, DESCRIPTIONS, AND TITLES MAY NOT ACCURATELY REPRESENT THE PRODUCT. WE ENCOURAGE YOU TO CONFIRM THAT THE MANUFACTURER'S ITEM CODE MATCHES THE PRODUCTS YOU ARE SEEKING.",
      'ALL PATIENTS OR HOME USERS SHOULD CONSULT A PRESCRIPTION FOR ANY MEDICAL SUPPLIES OR DEVICES THAT REQUIRE ONE. CERTAIN PRODUCTS MAY HAVE A SPECIFIC SHIPPING REQUIREMENTS DUE TO WEIGHT AND REFRIGERATION.',
      'PLEASE REFER TO OUR SHIPPING PAGE FOR DETAILS. ALL PRODUCTS ON THIS WEBSITE ARE SUBJECT TO CURRENT MANUFACTURER PRICING CHANGES AND AVAILABILITY. IF YOU HAVE ANY QUESTIONS OR CONCERNS, PLEASE EMAIL OR CALL US AT 919-444-2339 FOR FURTHER ASSISTANCE.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Terms &amp; Conditions</h1>
      <div className={styles.subtitle}>ASii Terms &amp; Conditions</div>
      {TERMS_SECTIONS.map((section) => (
        <section key={section.title} className={styles.section}>
          <h2>{section.title}</h2>
          {section.body.map((paragraph, index) => (
            <p key={`${section.title}-${index}`}>{paragraph}</p>
          ))}
        </section>
      ))}
    </div>
  );
}
