name: Build Feature

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'

jobs: 
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run lint and formatting checks
        working-directory: ./server
        run: |
          npm run format:check
          npm run lint:check

      - name: Build project
        working-directory: ./server
        run: npm run build

  build-client:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Run lint and formatting checks
        working-directory: ./client
        run: |
          npm run format:check
          npm run lint:check

      - name: Build project
        working-directory: ./client
        run: npm run build

  test-server:
    runs-on: ubuntu-latest
    needs: build-server-feature
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run server unit tests
        working-directory: ./server
        run: npm run test

  test-client:
    runs-on: ubuntu-latest
    needs: build-client-feature
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Run client unit tests
        working-directory: client
        run: npm run test

      - name: Run client e2e tests
        working-directory: client
        run: npm run test:e2e