name: PROD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  deploy-server:
    needs: 
      - build-server
      - test-server
    runs-on: [self-hosted, linux, PROD]
    environment: PROD
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Backup docker image
        run: |
          docker image rm nsoteropoulos/asiimedical-server:backup
          docker image tag nsoteropoulos/asiimedical-server:latest nsoteropoulos/asiimedical-server:backup

      - name: Pull server image from docker hub
        run: docker pull nsoteropoulos/asiimedical-server

      - name: Delete old container
        run: docker rm -f asiimedical-server

      - name: Run docker container
        run: docker run -d -p 3000:3000 --env-file .env --name asiimedical-server nsoteropoulos/asiimedical-server
  
  deploy-client:
    needs: 
      - build-client
      - test-client
    runs-on: [self-hosted, linux, PROD]
    environment: PROD
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Backup docker image
        run: |
          docker image rm nsoteropoulos/asiimedical-server:backup
          docker image tag nsoteropoulos/asiimedical-server:latest nsoteropoulos/asiimedical-server:backup

      - name: Pull server image from docker hub
        run: docker pull nsoteropoulos/asiimedical-client

      - name: Delete old container
        run: docker rm -f asiimedical-client

      - name: Run docker container
        run: docker run -d -p 4000:4000 --env-file .env --name asiimedical-client nsoteropoulos/asiimedical-client

