name: PROD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  deploy-server:
    runs-on: [self-hosted, linux, PROD]
    environment: PROD
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Backup docker image
        run: |
          docker image rm nsoteropoulos/asiimedical-server:backup
          docker image tag nsoteropoulos/asiimedical-server:latest nsoteropoulos/asiimedical-server:backup

      - name: Pull server image from docker hub
        run: docker pull nsoteropoulos/asiimedical-server

      - name: Delete old container
        run: docker rm -f asiimedical-server

      - name: Run docker container
        run: docker run -d -p 3001:3001 --name asiimedical-server nsoteropoulos/asiimedical-server
  
  deploy-client:
    runs-on: [self-hosted, linux, PROD]
    environment: PROD
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Backup docker image
        run: |
          docker rmi nsoteropoulos/asiimedical-client:backup || true
          docker image tag nsoteropoulos/asiimedical-client:latest nsoteropoulos/asiimedical-client:backup

      - name: Pull server image from docker hub
        run: docker pull nsoteropoulos/asiimedical-client

      - name: Delete old container
        run: docker rm -f asiimedical-client

      - name: Create env file
        run: |
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
          echo "NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }}" >> .env

      - name: Run docker container
        run: docker run -d -p 3000:3000 --env-file .env --name asiimedical-client nsoteropoulos/asiimedical-client

