name: DEV Pipeline

on:
  push:
    branches:
      - develop

jobs: 
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./server
        run: echo "TEST_VAL=${{secrets.TEST_VAL}}" >> .env && echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Build docker image
        working-directory: ./server
        run: docker build -t nsoteropoulos/asiimedical-server .
      - name: Publish server image to docker hub
        working-directory: ./server
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker images
          docker push nsoteropoulos/asiimedical-server

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./client
        run: echo "TEST_VAL=${{secrets.TEST_VAL}}" >> .env && echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Build docker image
        working-directory: ./client
        run: docker build -t nsoteropoulos/asiimedical-client .
      - name: Publish client image to docker hub
        working-directory: ./client
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker images
          docker push nsoteropoulos/asiimedical-client

  test-server:
    runs-on: ubuntu-latest
    needs: build-server
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./server
        run: echo "TEST_VAL=${{secrets.TEST_VAL}}" >> .env && echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Install dependencies
        working-directory: ./server
        run: npm ci
      - name: Test server
        working-directory: ./server
        run: npm run test

  test-client:
    runs-on: ubuntu-latest
    needs: build-client
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./client
        run: echo "TEST_VAL=${{secrets.TEST_VAL}}" >> .env && echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Test client
        working-directory: client
        run: npm run test

  deploy-server:
    needs: 
      - build-server
      - test-server
    runs-on: [self-hosted, linux, DEV]
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull server image from docker hub
        run: docker pull nsoteropoulos/asiimedical-server
      - name: Delete old container
        run: docker rm -f asiimedical-server
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name asiimedical-server nsoteropoulos/asiimedical-server
  
  deploy-client:
    needs: 
      - build-client
      - test-client
    runs-on: [self-hosted, linux, DEV]
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull server image from docker hub
        run: docker pull nsoteropoulos/asiimedical-client
      - name: Delete old container
        run: docker rm -f asiimedical-client
      - name: Run docker container
        run: docker run -d -p 4000:4000 --name asiimedical-client nsoteropoulos/asiimedical-client

