name: Deploy application

on:
  push:
    branches:
      - develop

jobs: 
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./server
        run: echo "TEST_VAL=${{secrets.TEST_VAL}}" >> .env && echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Build docker image
        working-directory: ./server
        run: docker build -t nsoteropoulos/asiimedical-server .

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./client
        run: echo "TEST_VAL=${{secrets.TEST_VAL}}" >> .env && echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Build docker image
        working-directory: ./client
        run: docker build -t nsoteropoulos/asiimedical-client .

